import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

const buildInvoice = (doc, { appointment, user, doctor }) => {
  const primary = "#0f766e";
  const soft = "#ecfeff";
  const dark = "#0f172a";
  const gray = "#475569";
  const border = "#cbd5e1";

  /*HEADER BAR*/
  doc.rect(0, 0, 612, 130).fill(primary);

  const logoPath = path.join(process.cwd(), "assets", "logo.png");
  if (fs.existsSync(logoPath)) {
    doc.image(logoPath, 50, 35, { width: 55 });
  }

  doc
    .fillColor("white")
    .font("Helvetica-Bold")
    .fontSize(26)
    .text("MediQueue", 120, 38);

  doc
    .font("Helvetica")
    .fontSize(12)
    .fillColor("#d1fae5")
    .text("Hospital Appointment Invoice", 120, 72);

  /* INVOICE META */
  doc.roundedRect(380, 35, 180, 70, 8).fill("white");

  doc
    .fillColor(dark)
    .font("Helvetica-Bold")
    .fontSize(10)
    .text("INVOICE", 395, 45);

  doc
    .font("Helvetica")
    .fontSize(9)
    .text(`ID: ${appointment._id}`, 395, 60, { width: 160 })
    .text(`Date: ${new Date().toLocaleDateString()}`, 395, 74);

  doc.y = 160;

  /*  INFO CARDS  */
  twoColumnSection(
    doc,
    "Patient Information",
    [
      ["Name", user.name],
      ["Email", user.email],
    ],
    "Appointment Details",
    [
      ["Doctor", doctor.name],
      ["Specialty", doctor.specialty],
      ["Date", appointment.date],
      ["Time", appointment.time],
      ["Status", appointment.status.toUpperCase()],
    ],
  );

  doc.moveDown(2);

  /* PAYMENT SUMMARY  */
  const paymentY = doc.y;

  doc.roundedRect(50, paymentY, 510, 110, 10).fill(soft);

  doc
    .fillColor(primary)
    .font("Helvetica-Bold")
    .fontSize(14)
    .text("Payment Summary", 70, paymentY + 15);

  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor(dark)
    .text(`Payment ID: ${appointment.paymentIntentId}`, 70, paymentY + 40, {
      width: 300,
    })
    .text(
      `Payment Status: ${appointment.paymentStatus.toUpperCase()}`,
      70,
      paymentY + 60,
    );

  doc
    .font("Helvetica-Bold")
    .fontSize(18)
    .fillColor(primary)
    .text(`LKR ${doctor.fees}.00`, 0, paymentY + 48, {
      align: "right",
      width: 530,
    });

  doc.y = paymentY + 140;

  /* FOOTER  */
  doc
    .strokeColor(border)
    .lineWidth(1)
    .moveTo(50, doc.y)
    .lineTo(560, doc.y)
    .stroke();

  doc.moveDown(1);

  doc
    .fontSize(9)
    .fillColor(gray)
    .text(
      "This invoice is system-generated by MediQueue Hospital Appointment System.\nNo signature is required.",
      { align: "center", lineGap: 4 },
    );
};

/* STREAM PDF  */
export const streamInvoicePdf = (res, data) => {
  const doc = new PDFDocument({ margin: 50, size: "A4" });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=Mediqueue-Invoice-${data.appointment._id}.pdf`,
  );

  doc.pipe(res);
  buildInvoice(doc, data);
  doc.end();
};

/*BUFFER PDF */
export const generateInvoicePdfBuffer = async (data) => {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks = [];

    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    buildInvoice(doc, data);
    doc.end();
  });
};

const twoColumnSection = (doc, leftTitle, leftData, rightTitle, rightData) => {
  const startY = doc.y;

  const leftHeight = card(doc, 50, startY, 240, leftTitle, leftData);
  const rightHeight = card(doc, 320, startY, 240, rightTitle, rightData);

  doc.y = startY + Math.max(leftHeight, rightHeight) + 20;
};

const card = (doc, x, y, w, title, rows) => {
  let cursorY = y + 38;

  doc.roundedRect(x, y, w, rows.length * 26 + 42, 10).stroke("#cbd5e1");

  doc
    .font("Helvetica-Bold")
    .fontSize(13)
    .fillColor("#0f766e")
    .text(title, x + 15, y + 12);

  rows.forEach(([key, value]) => {
    doc
      .font("Helvetica-Bold")
      .fontSize(10)
      .fillColor("#0f172a")
      .text(`${key}:`, x + 15, cursorY, { width: 55 });

    doc
      .font("Helvetica")
      .fillColor("#475569")
      .text(value, x + 75, cursorY, {
        width: w - 90,
        lineGap: 2,
      });

    cursorY = doc.y + 6;
  });

  return cursorY - y;
};
